version: '3.8'

# Variáveis de ambiente padrão - ATUALIZADAS para Vite
x-environment: &default-environment
  VITE_PORT: 3000
  VITE_APP_API_URL: http://localhost:3001
  NODE_ENV: development

services:
  # Aplicação React com Vite
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3050}:${VITE_PORT:-3050}"
    environment:
      <<: *default-environment
      VITE_PORT: ${VITE_PORT:-3050}
      PORT: ${VITE_PORT:-3050}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    healthcheck:
      # Healthcheck atualizado para Vite
      test: ["CMD", "curl", "-f", "http://localhost:${VITE_PORT:-3050}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Futuro serviço de API
  # api:
  #   build: ./api
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: